/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    Imput: typeof import('./resources/js/Components/imput.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    Test: typeof import('./resources/js/Components/test.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    UiAlert: typeof import('./resources/js/Components/Ui/Alert.vue')['default']
    UiCard: typeof import('./resources/js/Components/Ui/Card.vue')['default']
    UiImput: typeof import('./resources/js/Components/Ui/imput.vue')['default']
    UiInput: typeof import('./resources/js/Components/Ui/Input.vue')['default']
    UiToogle: typeof import('./resources/js/Components/Ui/Toogle.vue')['default']
  }
}
