services:
  # ===========================
  # 🐘 Backend (Laravel App)
  # ===========================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: novacms_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - novanet

  # ===========================
  # 🎨 Frontend (Vite + Vue)
  # ===========================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: novacms_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - novanet
    depends_on:
      - app
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - VITE_APP_URL=http://localhost:8080

  # ===========================
  # 🌐 Nginx Reverse Proxy
  # ===========================
  nginx:
    image: nginx:latest
    container_name: novacms_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - frontend
    networks:
      - novanet

# ===========================
# 🌍 Networks & Volumes
# ===========================
networks:
  novanet:

volumes:
  node_modules_cache:
